"""empty message

Revision ID: 4d76bc5757c4
Revises: cbf679ea3b69
Create Date: 2024-07-30 14:43:15.955103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d76bc5757c4'
down_revision = 'cbf679ea3b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_payment', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('next_payment')

    # ### end Alembic commands ###
