"""empty message

Revision ID: cbf679ea3b69
Revises: 1d78df5266f2
Create Date: 2024-07-30 14:28:27.586586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf679ea3b69'
down_revision = '1d78df5266f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payed_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('subscription_type')
        batch_op.drop_column('payed_by')

    # ### end Alembic commands ###
